# Generated by Django 4.0.6 on 2022-07-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='athletes',
        ),
    ]
