# Generated by Django 4.0.6 on 2022-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_tournaments_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='price',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
