# Generated by Django 4.0.6 on 2022-07-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
